export const AUTHORIZED_KHADEM_REQUEST = "AUTHORIZED_KHADEM_REQUEST"
export const AUTHORIZED_KHADEM_SUCCESS = "AUTHORIZED_KHADEM_SUCCESS"
export const AUTHORIZED_KHADEM_FAIL = "AUTHORIZED_KHADEM_FAIL"
