export const BIBLE_MCQ_UPDATE_REQUEST = "BIBLE_MCQ_UPDATE_REQUEST"
export const BIBLE_MCQ_UPDATE_SUCCESS = "BIBLE_MCQ_UPDATE_SUCCESS"
export const BIBLE_MCQ_UPDATE_FAIL = "BIBLE_MCQ_UPDATE_FAIL"

export const BIBLE_MCQ_DELETE_REQUEST = "BIBLE_MCQ_DELETE_REQUEST"
export const BIBLE_MCQ_DELETE_SUCCESS = "BIBLE_MCQ_DELETE_SUCCESS"
export const BIBLE_MCQ_DELETE_FAIL = "BIBLE_MCQ_DELETE_FAIL"
