// Church list
export const CHURCH_LIST_REQUEST = 'CHURCH_LIST_REQUEST'
export const CHURCH_LIST_SUCCESS = 'CHURCH_LIST_SUCCESS'
export const CHURCH_LIST_FAIL = 'CHURCH_LIST_FAIL'

// Church details
export const CHURCH_DETAILS_REQUEST = 'CHURCH_DETAILS_REQUEST'
export const CHURCH_DETAILS_SUCCESS = 'CHURCH_DETAILS_SUCCESS'
export const CHURCH_DETAILS_FAIL = 'CHURCH_DETAILS_FAIL'

// Church create
export const CHURCH_CREATE_REQUEST = 'CHURCH_CREATE_REQUEST'
export const CHURCH_CREATE_SUCCESS = 'CHURCH_CREATE_SUCCESS'
export const CHURCH_CREATE_FAIL = 'CHURCH_CREATE_FAIL'
export const CHURCH_CREATE_RESET = 'CHURCH_CREATE_RESET'

// Church update
export const CHURCH_UPDATE_REQUEST = 'CHURCH_UPDATE_REQUEST'
export const CHURCH_UPDATE_SUCCESS = 'CHURCH_UPDATE_SUCCESS'
export const CHURCH_UPDATE_FAIL = 'CHURCH_UPDATE_FAIL'
export const CHURCH_UPDATE_RESET = 'CHURCH_UPDATE_RESET'

// Church delete
export const CHURCH_DELETE_REQUEST = 'CHURCH_DELETE_REQUEST'
export const CHURCH_DELETE_SUCCESS = 'CHURCH_DELETE_SUCCESS'
export const CHURCH_DELETE_FAIL = 'CHURCH_DELETE_FAIL'
export const CHURCH_DELETE_RESET = 'CHURCH_DELETE_RESET'
