// Class List Constants
export const CLASS_LIST_REQUEST = 'CLASS_LIST_REQUEST'
export const CLASS_LIST_SUCCESS = 'CLASS_LIST_SUCCESS'
export const CLASS_LIST_FAIL = 'CLASS_LIST_FAIL'
export const CLASS_LIST_RESET = 'CLASS_LIST_RESET'

// Class Create Constants
export const CLASS_CREATE_REQUEST = 'CLASS_CREATE_REQUEST'
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS'
export const CLASS_CREATE_FAIL = 'CLASS_CREATE_FAIL'
export const CLASS_CREATE_RESET = 'CLASS_CREATE_RESET'

// Class Update Constants
export const CLASS_UPDATE_REQUEST = 'CLASS_UPDATE_REQUEST'
export const CLASS_UPDATE_SUCCESS = 'CLASS_UPDATE_SUCCESS'
export const CLASS_UPDATE_FAIL = 'CLASS_UPDATE_FAIL'
export const CLASS_UPDATE_RESET = 'CLASS_UPDATE_RESET'

// Class Details Constants
export const CLASS_DETAILS_REQUEST = 'CLASS_DETAILS_REQUEST'
export const CLASS_DETAILS_SUCCESS = 'CLASS_DETAILS_SUCCESS'
export const CLASS_DETAILS_FAIL = 'CLASS_DETAILS_FAIL'
export const CLASS_DETAILS_RESET = 'CLASS_DETAILS_RESET'