export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

export const GET_COMMUNICATION_HISTORY_REQUEST = "GET_COMMUNICATION_HISTORY_REQUEST";
export const GET_COMMUNICATION_HISTORY_SUCCESS = "GET_COMMUNICATION_HISTORY_SUCCESS";
export const GET_COMMUNICATION_HISTORY_FAIL = "GET_COMMUNICATION_HISTORY_FAIL";
