// MCQ List
export const MCQ_LIST_REQUEST = 'MCQ_LIST_REQUEST'
export const MCQ_LIST_SUCCESS = 'MCQ_LIST_SUCCESS'
export const MCQ_LIST_FAIL = 'MCQ_LIST_FAIL'

// MCQ Create
export const MCQ_CREATE_REQUEST = "MCQ_CREATE_REQUEST"
export const MCQ_CREATE_SUCCESS = "MCQ_CREATE_SUCCESS"
export const MCQ_CREATE_FAIL = "MCQ_CREATE_FAIL"
export const MCQ_CREATE_RESET = 'MCQ_CREATE_RESET'

// MCQ Get Single
export const MCQ_GET_REQUEST = "MCQ_GET_REQUEST"
export const MCQ_GET_SUCCESS = "MCQ_GET_SUCCESS"
export const MCQ_GET_FAIL = "MCQ_GET_FAIL"

// MCQ Update
export const MCQ_UPDATE_REQUEST = "MCQ_UPDATE_REQUEST"
export const MCQ_UPDATE_SUCCESS = "MCQ_UPDATE_SUCCESS"
export const MCQ_UPDATE_FAIL = "MCQ_UPDATE_FAIL"
export const MCQ_UPDATE_RESET = 'MCQ_UPDATE_RESET'

// MCQ Delete
export const MCQ_DELETE_REQUEST = "MCQ_DELETE_REQUEST"
export const MCQ_DELETE_SUCCESS = "MCQ_DELETE_SUCCESS"
export const MCQ_DELETE_FAIL = "MCQ_DELETE_FAIL"

// MCQ Answer Submit
export const MCQ_ANSWER_SUBMIT_REQUEST = 'MCQ_ANSWER_SUBMIT_REQUEST'
export const MCQ_ANSWER_SUBMIT_SUCCESS = 'MCQ_ANSWER_SUBMIT_SUCCESS'
export const MCQ_ANSWER_SUBMIT_FAIL = 'MCQ_ANSWER_SUBMIT_FAIL'
export const MCQ_ANSWER_SUBMIT_RESET = 'MCQ_ANSWER_SUBMIT_RESET'

// MCQ Answer List
export const MCQ_ANSWER_LIST_REQUEST = 'MCQ_ANSWER_LIST_REQUEST'
export const MCQ_ANSWER_LIST_SUCCESS = 'MCQ_ANSWER_LIST_SUCCESS'
export const MCQ_ANSWER_LIST_FAIL = 'MCQ_ANSWER_LIST_FAIL'

// MCQ Sort Types
export const MCQ_SORT_TYPE = {
  ASCENDING: 'ASCENDING',
  DESCENDING: 'DESCENDING'
}

// MCQ Order Types
export const MCQ_ORDER_TYPE = {
  CREATED_AT: 'createdAt',
  CHAPTER: 'chapter',
  FROM_VERSE: 'fromVerse',
  START_DATE: 'startDate',
  END_DATE: 'endDate',
  POINTS: 'points'
}
