// ServiceBook list constants
export const SERVICEBOOK_LIST_REQUEST = 'SERVICEBOOK_LIST_REQUEST'
export const SERVICEBOOK_LIST_SUCCESS = 'SERVICEBOOK_LIST_SUCCESS'
export const SERVICEBOOK_LIST_FAIL = 'SERVICEBOOK_LIST_FAIL'

// ServiceBook create constants
export const SERVICEBOOK_CREATE_REQUEST = 'SERVICEBOOK_CREATE_REQUEST'
export const SERVICEBOOK_CREATE_SUCCESS = 'SERVICEBOOK_CREATE_SUCCESS'
export const SERVICEBOOK_CREATE_FAIL = 'SERVICEBOOK_CREATE_FAIL'
export const SERVICEBOOK_CREATE_RESET = 'SERVICEBOOK_CREATE_RESET'

// ServiceBook update constants
export const SERVICEBOOK_UPDATE_REQUEST = 'SERVICEBOOK_UPDATE_REQUEST'
export const SERVICEBOOK_UPDATE_SUCCESS = 'SERVICEBOOK_UPDATE_SUCCESS'
export const SERVICEBOOK_UPDATE_FAIL = 'SERVICEBOOK_UPDATE_FAIL'
export const SERVICEBOOK_UPDATE_RESET = 'SERVICEBOOK_UPDATE_RESET'

// ServiceBook details constants
export const SERVICEBOOK_DETAILS_REQUEST = 'SERVICEBOOK_DETAILS_REQUEST'
export const SERVICEBOOK_DETAILS_SUCCESS = 'SERVICEBOOK_DETAILS_SUCCESS'
export const SERVICEBOOK_DETAILS_FAIL = 'SERVICEBOOK_DETAILS_FAIL'