export const SHABAB_EVENT_REGISTER_REQUEST = "SHABAB_EVENT_REGISTER_REQUEST"
export const SHABAB_EVENT_REGISTER_SUCCESS = "SHABAB_EVENT_REGISTER_SUCCESS"
export const SHABAB_EVENT_REGISTER_FAIL = "SHABAB_EVENT_REGISTER_FAIL"
