export const USER_SERVICE_META_REQUEST = "USER_SERVICE_META_REQUEST"
export const USER_SERVICE_META_SUCCESS = "USER_SERVICE_META_SUCCESS"
export const USER_SERVICE_META_FAIL = "USER_SERVICE_META_FAIL"

export const USER_FOLLOW_UP_UPDATE_REQUEST = "USER_FOLLOW_UP_UPDATE_REQUEST"
export const USER_FOLLOW_UP_UPDATE_SUCCESS = "USER_FOLLOW_UP_UPDATE_SUCCESS"
export const USER_FOLLOW_UP_UPDATE_FAIL = "USER_FOLLOW_UP_UPDATE_FAIL"
